filebeat.autodiscover:
  providers:
    - type: docker
      host: unix:///var/run/docker.sock
      hints.enabled: true
      templates:
        - condition:
            has_fields: ['docker.container.id']
          config:
            - type: filestream
              id: container-${data.docker.container.id}
              prospector.scanner.symlinks: true
              parsers:
                - container:
                    stream: all
                    format: docker
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
  - add_docker_metadata:
      host: unix:///var/run/docker.sock

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
