input {
  beats {
    port => 5044
  }
}

filter {
  if [docker] and [docker][container] and [docker][container][name] {
    mutate {
      add_field => { "container_name" => "%{[docker][container][name]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sophie-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
